# -*- coding: utf-8 -*-

countries_data = [
    {
        'name': u'Afghanistan',
        'alpha2': u'AF',
        'alpha3': u'AFG',
        'numeric': 4,
        'independent': True,
    },
    {
        'name': u'Åland Islands',
        'alpha2': u'AX',
        'alpha3': u'ALA',
        'numeric': 248,
        'independent': False,
    },
    {
        'name': u'Albania',
        'alpha2': u'AL',
        'alpha3': u'ALB',
        'numeric': 8,
        'independent': True,
    },
    {
        'name': u'Algeria',
        'alpha2': u'DZ',
        'alpha3': u'DZA',
        'numeric': 12,
        'independent': True,
    },
    {
        'name': u'American Samoa',
        'alpha2': u'AS',
        'alpha3': u'ASM',
        'numeric': 16,
        'independent': False,
    },
    {
        'name': u'Andorra',
        'alpha2': u'AD',
        'alpha3': u'AND',
        'numeric': 20,
        'independent': True,
    },
    {
        'name': u'Angola',
        'alpha2': u'AO',
        'alpha3': u'AGO',
        'numeric': 24,
        'independent': True,
    },
    {
        'name': u'Anguilla',
        'alpha2': u'AI',
        'alpha3': u'AIA',
        'numeric': 660,
        'independent': False,
    },
    {
        'name': u'Antarctica',
        'alpha2': u'AQ',
        'alpha3': u'ATA',
        'numeric': 10,
        'independent': False,
    },
    {
        'name': u'Antigua and Barbuda',
        'alpha2': u'AG',
        'alpha3': u'ATG',
        'numeric': 28,
        'independent': True,
    },
    {
        'name': u'Argentina',
        'alpha2': u'AR',
        'alpha3': u'ARG',
        'numeric': 32,
        'independent': True,
    },
    {
        'name': u'Armenia',
        'alpha2': u'AM',
        'alpha3': u'ARM',
        'numeric': 51,
        'independent': True,
    },
    {
        'name': u'Aruba',
        'alpha2': u'AW',
        'alpha3': u'ABW',
        'numeric': 533,
        'independent': False,
    },
    {
        'name': u'Australia',
        'alpha2': u'AU',
        'alpha3': u'AUS',
        'numeric': 36,
        'independent': True,
    },
    {
        'name': u'Austria',
        'alpha2': u'AT',
        'alpha3': u'AUT',
        'numeric': 40,
        'independent': True,
    },
    {
        'name': u'Azerbaijan',
        'alpha2': u'AZ',
        'alpha3': u'AZE',
        'numeric': 31,
        'independent': True,
    },
    {
        'name': u'Bahamas',
        'alpha2': u'BS',
        'alpha3': u'BHS',
        'numeric': 44,
        'independent': True,
    },
    {
        'name': u'Bahrain',
        'alpha2': u'BH',
        'alpha3': u'BHR',
        'numeric': 48,
        'independent': True,
    },
    {
        'name': u'Bangladesh',
        'alpha2': u'BD',
        'alpha3': u'BGD',
        'numeric': 50,
        'independent': True,
    },
    {
        'name': u'Barbados',
        'alpha2': u'BB',
        'alpha3': u'BRB',
        'numeric': 52,
        'independent': True,
    },
    {
        'name': u'Belarus',
        'alpha2': u'BY',
        'alpha3': u'BLR',
        'numeric': 112,
        'independent': True,
    },
    {
        'name': u'Belgium',
        'alpha2': u'BE',
        'alpha3': u'BEL',
        'numeric': 56,
        'independent': True,
    },
    {
        'name': u'Belize',
        'alpha2': u'BZ',
        'alpha3': u'BLZ',
        'numeric': 84,
        'independent': True,
    },
    {
        'name': u'Benin',
        'alpha2': u'BJ',
        'alpha3': u'BEN',
        'numeric': 204,
        'independent': True,
    },
    {
        'name': u'Bermuda',
        'alpha2': u'BM',
        'alpha3': u'BMU',
        'numeric': 60,
        'independent': False,
    },
    {
        'name': u'Bhutan',
        'alpha2': u'BT',
        'alpha3': u'BTN',
        'numeric': 64,
        'independent': True,
    },
    {
        'name': u'Bolivia (Plurinational State of)',
        'alpha2': u'BO',
        'alpha3': u'BOL',
        'numeric': 68,
        'independent': True,
    },
    {
        'name': u'"Bonaire, Sint Eustatius and Saba"',
        'alpha2': u'BQ',
        'alpha3': u'BES',
        'numeric': 535,
        'independent': False,
    },
    {
        'name': u'Bosnia and Herzegovina',
        'alpha2': u'BA',
        'alpha3': u'BIH',
        'numeric': 70,
        'independent': True,
    },
    {
        'name': u'Botswana',
        'alpha2': u'BW',
        'alpha3': u'BWA',
        'numeric': 72,
        'independent': True,
    },
    {
        'name': u'Bouvet Island',
        'alpha2': u'BV',
        'alpha3': u'BVT',
        'numeric': 74,
        'independent': False,
    },
    {
        'name': u'Brazil',
        'alpha2': u'BR',
        'alpha3': u'BRA',
        'numeric': 76,
        'independent': True,
    },
    {
        'name': u'British Indian Ocean Territory',
        'alpha2': u'IO',
        'alpha3': u'IOT',
        'numeric': 86,
        'independent': False,
    },
    {
        'name': u'Brunei Darussalam',
        'alpha2': u'BN',
        'alpha3': u'BRN',
        'numeric': 96,
        'independent': True,
    },
    {
        'name': u'Bulgaria',
        'alpha2': u'BG',
        'alpha3': u'BGR',
        'numeric': 100,
        'independent': True,
    },
    {
        'name': u'Burkina Faso',
        'alpha2': u'BF',
        'alpha3': u'BFA',
        'numeric': 854,
        'independent': True,
    },
    {
        'name': u'Burundi',
        'alpha2': u'BI',
        'alpha3': u'BDI',
        'numeric': 108,
        'independent': True,
    },
    {
        'name': u'Cabo Verde',
        'alpha2': u'CV',
        'alpha3': u'CPV',
        'numeric': 132,
        'independent': True,
    },
    {
        'name': u'Cambodia',
        'alpha2': u'KH',
        'alpha3': u'KHM',
        'numeric': 116,
        'independent': True,
    },
    {
        'name': u'Cameroon',
        'alpha2': u'CM',
        'alpha3': u'CMR',
        'numeric': 120,
        'independent': True,
    },
    {
        'name': u'Canada',
        'alpha2': u'CA',
        'alpha3': u'CAN',
        'numeric': 124,
        'independent': True,
    },
    {
        'name': u'Cayman Islands',
        'alpha2': u'KY',
        'alpha3': u'CYM',
        'numeric': 136,
        'independent': True,
    },
    {
        'name': u'Central African Republic',
        'alpha2': u'CF',
        'alpha3': u'CAF',
        'numeric': 140,
        'independent': True,
    },
    {
        'name': u'Chad',
        'alpha2': u'TD',
        'alpha3': u'TCD',
        'numeric': 148,
        'independent': True,
    },
    {
        'name': u'Chile',
        'alpha2': u'CL',
        'alpha3': u'CHL',
        'numeric': 152,
        'independent': True,
    },
    {
        'name': u'China',
        'alpha2': u'CN',
        'alpha3': u'CHN',
        'numeric': 156,
        'independent': True,
    },
    {
        'name': u'Christmas Island',
        'alpha2': u'CX',
        'alpha3': u'CXR',
        'numeric': 162,
        'independent': False,
    },
    {
        'name': u'Cocos (Keeling) Islands',
        'alpha2': u'CC',
        'alpha3': u'CCK',
        'numeric': 166,
        'independent': False,
    },
    {
        'name': u'Colombia',
        'alpha2': u'CO',
        'alpha3': u'COL',
        'numeric': 170,
        'independent': True,
    },
    {
        'name': u'Comoros',
        'alpha2': u'KM',
        'alpha3': u'COM',
        'numeric': 174,
        'independent': True,
    },
    {
        'name': u'Congo',
        'alpha2': u'CG',
        'alpha3': u'COG',
        'numeric': 178,
        'independent': True,
    },
    {
        'name': u'Congo (Democratic Republic of the)',
        'alpha2': u'CD',
        'alpha3': u'COD',
        'numeric': 180,
        'independent': True,
    },
    {
        'name': u'Cook Islands',
        'alpha2': u'CK',
        'alpha3': u'COK',
        'numeric': 184,
        'independent': False,
    },
    {
        'name': u'Costa Rica',
        'alpha2': u'CR',
        'alpha3': u'CRI',
        'numeric': 188,
        'independent': True,
    },
    {
        'name': u'Côte d\'Ivoire',
        'alpha2': u'CI',
        'alpha3': u'CIV',
        'numeric': 384,
        'independent': True,
    },
    {
        'name': u'Croatia',
        'alpha2': u'HR',
        'alpha3': u'HRV',
        'numeric': 191,
        'independent': True,
    },
    {
        'name': u'Cuba',
        'alpha2': u'CU',
        'alpha3': u'CUB',
        'numeric': 192,
        'independent': True,
    },
    {
        'name': u'Curaçao',
        'alpha2': u'CW',
        'alpha3': u'CUW',
        'numeric': 531,
        'independent': False,
    },
    {
        'name': u'Cyprus',
        'alpha2': u'CY',
        'alpha3': u'CYP',
        'numeric': 196,
        'independent': True,
    },
    {
        'name': u'Czechia',
        'alpha2': u'CZ',
        'alpha3': u'CZE',
        'numeric': 203,
        'independent': True,
    },
    {
        'name': u'Denmark',
        'alpha2': u'DK',
        'alpha3': u'DNK',
        'numeric': 208,
        'independent': True,
    },
    {
        'name': u'Djibouti',
        'alpha2': u'DJ',
        'alpha3': u'DJI',
        'numeric': 262,
        'independent': True,
    },
    {
        'name': u'Dominica',
        'alpha2': u'DM',
        'alpha3': u'DMA',
        'numeric': 212,
        'independent': True,
    },
    {
        'name': u'Dominican Republic',
        'alpha2': u'DO',
        'alpha3': u'DOM',
        'numeric': 214,
        'independent': True,
    },
    {
        'name': u'Ecuador',
        'alpha2': u'EC',
        'alpha3': u'ECU',
        'numeric': 218,
        'independent': True,
    },
    {
        'name': u'Egypt',
        'alpha2': u'EG',
        'alpha3': u'EGY',
        'numeric': 818,
        'independent': True,
    },
    {
        'name': u'El Salvador',
        'alpha2': u'SV',
        'alpha3': u'SLV',
        'numeric': 222,
        'independent': True,
    },
    {
        'name': u'Equatorial Guinea',
        'alpha2': u'GQ',
        'alpha3': u'GNQ',
        'numeric': 226,
        'independent': True,
    },
    {
        'name': u'Eritrea',
        'alpha2': u'ER',
        'alpha3': u'ERI',
        'numeric': 232,
        'independent': True,
    },
    {
        'name': u'Estonia',
        'alpha2': u'EE',
        'alpha3': u'EST',
        'numeric': 233,
        'independent': True,
    },
    {
        'name': u'Ethiopia',
        'alpha2': u'ET',
        'alpha3': u'ETH',
        'numeric': 231,
        'independent': True,
    },
    {
        'name': u'Falkland Islands (Malvinas)',
        'alpha2': u'FK',
        'alpha3': u'FLK',
        'numeric': 238,
        'independent': False,
    },
    {
        'name': u'Faroe Islands',
        'alpha2': u'FO',
        'alpha3': u'FRO',
        'numeric': 234,
        'independent': False,
    },
    {
        'name': u'Fiji',
        'alpha2': u'FJ',
        'alpha3': u'FJI',
        'numeric': 242,
        'independent': True,
    },
    {
        'name': u'Finland',
        'alpha2': u'FI',
        'alpha3': u'FIN',
        'numeric': 246,
        'independent': True,
    },
    {
        'name': u'France',
        'alpha2': u'FR',
        'alpha3': u'FRA',
        'numeric': 250,
        'independent': True,
    },
    {
        'name': u'French Guiana',
        'alpha2': u'GF',
        'alpha3': u'GUF',
        'numeric': 254,
        'independent': False,
    },
    {
        'name': u'French Polynesia',
        'alpha2': u'PF',
        'alpha3': u'PYF',
        'numeric': 258,
        'independent': False,
    },
    {
        'name': u'French Southern Territories',
        'alpha2': u'TF',
        'alpha3': u'ATF',
        'numeric': 260,
        'independent': False,
    },
    {
        'name': u'Gabon',
        'alpha2': u'GA',
        'alpha3': u'GAB',
        'numeric': 266,
        'independent': True,
    },
    {
        'name': u'Gambia',
        'alpha2': u'GM',
        'alpha3': u'GMB',
        'numeric': 270,
        'independent': True,
    },
    {
        'name': u'Georgia',
        'alpha2': u'GE',
        'alpha3': u'GEO',
        'numeric': 268,
        'independent': True,
    },
    {
        'name': u'Germany',
        'alpha2': u'DE',
        'alpha3': u'DEU',
        'numeric': 276,
        'independent': True,
    },
    {
        'name': u'Ghana',
        'alpha2': u'GH',
        'alpha3': u'GHA',
        'numeric': 288,
        'independent': True,
    },
    {
        'name': u'Gibraltar',
        'alpha2': u'GI',
        'alpha3': u'GIB',
        'numeric': 292,
        'independent': True,
    },
    {
        'name': u'Greece',
        'alpha2': u'GR',
        'alpha3': u'GRC',
        'numeric': 300,
        'independent': True,
    },
    {
        'name': u'Greenland',
        'alpha2': u'GL',
        'alpha3': u'GRL',
        'numeric': 304,
        'independent': False,
    },
    {
        'name': u'Grenada',
        'alpha2': u'GD',
        'alpha3': u'GRD',
        'numeric': 308,
        'independent': True,
    },
    {
        'name': u'Guadeloupe',
        'alpha2': u'GP',
        'alpha3': u'GLP',
        'numeric': 312,
        'independent': False,
    },
    {
        'name': u'Guam',
        'alpha2': u'GU',
        'alpha3': u'GUM',
        'numeric': 316,
        'independent': False,
    },
    {
        'name': u'Guatemala',
        'alpha2': u'GT',
        'alpha3': u'GTM',
        'numeric': 320,
        'independent': True,
    },
    {
        'name': u'Guernsey',
        'alpha2': u'GG',
        'alpha3': u'GGY',
        'numeric': 831,
        'independent': False,
    },
    {
        'name': u'Guinea',
        'alpha2': u'GN',
        'alpha3': u'GIN',
        'numeric': 324,
        'independent': True,
    },
    {
        'name': u'Guinea-Bissau',
        'alpha2': u'GW',
        'alpha3': u'GNB',
        'numeric': 624,
        'independent': True,
    },
    {
        'name': u'Guyana',
        'alpha2': u'GY',
        'alpha3': u'GUY',
        'numeric': 328,
        'independent': True,
    },
    {
        'name': u'Haiti',
        'alpha2': u'HT',
        'alpha3': u'HTI',
        'numeric': 332,
        'independent': True,
    },
    {
        'name': u'Heard Island and McDonald Islands',
        'alpha2': u'HM',
        'alpha3': u'HMD',
        'numeric': 334,
        'independent': False,
    },
    {
        'name': u'Holy See',
        'alpha2': u'VA',
        'alpha3': u'VAT',
        'numeric': 336,
        'independent': True,
    },
    {
        'name': u'Honduras',
        'alpha2': u'HN',
        'alpha3': u'HND',
        'numeric': 340,
        'independent': True,
    },
    {
        'name': u'Hong Kong',
        'alpha2': u'HK',
        'alpha3': u'HKG',
        'numeric': 344,
        'independent': False,
    },
    {
        'name': u'Hungary',
        'alpha2': u'HU',
        'alpha3': u'HUN',
        'numeric': 348,
        'independent': True,
    },
    {
        'name': u'Iceland',
        'alpha2': u'IS',
        'alpha3': u'ISL',
        'numeric': 352,
        'independent': True,
    },
    {
        'name': u'India',
        'alpha2': u'IN',
        'alpha3': u'IND',
        'numeric': 356,
        'independent': True,
    },
    {
        'name': u'Indonesia',
        'alpha2': u'ID',
        'alpha3': u'IDN',
        'numeric': 360,
        'independent': True,
    },
    {
        'name': u'Iran (Islamic Republic of)',
        'alpha2': u'IR',
        'alpha3': u'IRN',
        'numeric': 364,
        'independent': True,
    },
    {
        'name': u'Iraq',
        'alpha2': u'IQ',
        'alpha3': u'IRQ',
        'numeric': 368,
        'independent': True,
    },
    {
        'name': u'Ireland',
        'alpha2': u'IE',
        'alpha3': u'IRL',
        'numeric': 372,
        'independent': True,
    },
    {
        'name': u'Isle of Man',
        'alpha2': u'IM',
        'alpha3': u'IMN',
        'numeric': 833,
        'independent': False,
    },
    {
        'name': u'Israel',
        'alpha2': u'IL',
        'alpha3': u'ISR',
        'numeric': 376,
        'independent': True,
    },
    {
        'name': u'Italy',
        'alpha2': u'IT',
        'alpha3': u'ITA',
        'numeric': 380,
        'independent': True,
    },
    {
        'name': u'Jamaica',
        'alpha2': u'JM',
        'alpha3': u'JAM',
        'numeric': 388,
        'independent': True,
    },
    {
        'name': u'Japan',
        'alpha2': u'JP',
        'alpha3': u'JPN',
        'numeric': 392,
        'independent': True,
    },
    {
        'name': u'Jersey',
        'alpha2': u'JE',
        'alpha3': u'JEY',
        'numeric': 832,
        'independent': False,
    },
    {
        'name': u'Jordan',
        'alpha2': u'JO',
        'alpha3': u'JOR',
        'numeric': 400,
        'independent': True,
    },
    {
        'name': u'Kazakhstan',
        'alpha2': u'KZ',
        'alpha3': u'KAZ',
        'numeric': 398,
        'independent': True,
    },
    {
        'name': u'Kenya',
        'alpha2': u'KE',
        'alpha3': u'KEN',
        'numeric': 404,
        'independent': True,
    },
    {
        'name': u'Kiribati',
        'alpha2': u'KI',
        'alpha3': u'KIR',
        'numeric': 296,
        'independent': True,
    },
    {
        'name': u'Korea (Democratic People\'s Republic of)',
        'alpha2': u'KP',
        'alpha3': u'PRK',
        'numeric': 408,
        'independent': True,
    },
    {
        'name': u'Korea (Republic of)',
        'alpha2': u'KR',
        'alpha3': u'KOR',
        'numeric': 410,
        'independent': True,
    },
    {
        'name': u'Kuwait',
        'alpha2': u'KW',
        'alpha3': u'KWT',
        'numeric': 414,
        'independent': True,
    },
    {
        'name': u'Kyrgyzstan',
        'alpha2': u'KG',
        'alpha3': u'KGZ',
        'numeric': 417,
        'independent': True,
    },
    {
        'name': u'Lao People\'s Democratic Republic',
        'alpha2': u'LA',
        'alpha3': u'LAO',
        'numeric': 418,
        'independent': True,
    },
    {
        'name': u'Latvia',
        'alpha2': u'LV',
        'alpha3': u'LVA',
        'numeric': 428,
        'independent': True,
    },
    {
        'name': u'Lebanon',
        'alpha2': u'LB',
        'alpha3': u'LBN',
        'numeric': 422,
        'independent': True,
    },
    {
        'name': u'Lesotho',
        'alpha2': u'LS',
        'alpha3': u'LSO',
        'numeric': 426,
        'independent': True,
    },
    {
        'name': u'Liberia',
        'alpha2': u'LR',
        'alpha3': u'LBR',
        'numeric': 430,
        'independent': True,
    },
    {
        'name': u'Libya',
        'alpha2': u'LY',
        'alpha3': u'LBY',
        'numeric': 434,
        'independent': True,
    },
    {
        'name': u'Liechtenstein',
        'alpha2': u'LI',
        'alpha3': u'LIE',
        'numeric': 438,
        'independent': True,
    },
    {
        'name': u'Lithuania',
        'alpha2': u'LT',
        'alpha3': u'LTU',
        'numeric': 440,
        'independent': True,
    },
    {
        'name': u'Luxembourg',
        'alpha2': u'LU',
        'alpha3': u'LUX',
        'numeric': 442,
        'independent': True,
    },
    {
        'name': u'Macao',
        'alpha2': u'MO',
        'alpha3': u'MAC',
        'numeric': 446,
        'independent': False,
    },
    {
        'name': u'Macedonia (the former Yugoslav Republic of)',
        'alpha2': u'MK',
        'alpha3': u'MKD',
        'numeric': 807,
        'independent': True,
    },
    {
        'name': u'Madagascar',
        'alpha2': u'MG',
        'alpha3': u'MDG',
        'numeric': 450,
        'independent': True,
    },
    {
        'name': u'Malawi',
        'alpha2': u'MW',
        'alpha3': u'MWI',
        'numeric': 454,
        'independent': True,
    },
    {
        'name': u'Malaysia',
        'alpha2': u'MY',
        'alpha3': u'MYS',
        'numeric': 458,
        'independent': True,
    },
    {
        'name': u'Maldives',
        'alpha2': u'MV',
        'alpha3': u'MDV',
        'numeric': 462,
        'independent': True,
    },
    {
        'name': u'Mali',
        'alpha2': u'ML',
        'alpha3': u'MLI',
        'numeric': 466,
        'independent': True,
    },
    {
        'name': u'Malta',
        'alpha2': u'MT',
        'alpha3': u'MLT',
        'numeric': 470,
        'independent': True,
    },
    {
        'name': u'Marshall Islands',
        'alpha2': u'MH',
        'alpha3': u'MHL',
        'numeric': 584,
        'independent': True,
    },
    {
        'name': u'Martinique',
        'alpha2': u'MQ',
        'alpha3': u'MTQ',
        'numeric': 474,
        'independent': False,
    },
    {
        'name': u'Mauritania',
        'alpha2': u'MR',
        'alpha3': u'MRT',
        'numeric': 478,
        'independent': True,
    },
    {
        'name': u'Mauritius',
        'alpha2': u'MU',
        'alpha3': u'MUS',
        'numeric': 480,
        'independent': True,
    },
    {
        'name': u'Mayotte',
        'alpha2': u'YT',
        'alpha3': u'MYT',
        'numeric': 175,
        'independent': False,
    },
    {
        'name': u'Mexico',
        'alpha2': u'MX',
        'alpha3': u'MEX',
        'numeric': 484,
        'independent': True,
    },
    {
        'name': u'Micronesia (Federated States of)',
        'alpha2': u'FM',
        'alpha3': u'FSM',
        'numeric': 583,
        'independent': True,
    },
    {
        'name': u'Moldova (Republic of)',
        'alpha2': u'MD',
        'alpha3': u'MDA',
        'numeric': 498,
        'independent': True,
    },
    {
        'name': u'Monaco',
        'alpha2': u'MC',
        'alpha3': u'MCO',
        'numeric': 492,
        'independent': True,
    },
    {
        'name': u'Mongolia',
        'alpha2': u'MN',
        'alpha3': u'MNG',
        'numeric': 496,
        'independent': True,
    },
    {
        'name': u'Montenegro',
        'alpha2': u'ME',
        'alpha3': u'MNE',
        'numeric': 499,
        'independent': True,
    },
    {
        'name': u'Montserrat',
        'alpha2': u'MS',
        'alpha3': u'MSR',
        'numeric': 500,
        'independent': False,
    },
    {
        'name': u'Morocco',
        'alpha2': u'MA',
        'alpha3': u'MAR',
        'numeric': 504,
        'independent': True,
    },
    {
        'name': u'Mozambique',
        'alpha2': u'MZ',
        'alpha3': u'MOZ',
        'numeric': 508,
        'independent': True,
    },
    {
        'name': u'Myanmar',
        'alpha2': u'MM',
        'alpha3': u'MMR',
        'numeric': 104,
        'independent': True,
    },
    {
        'name': u'Namibia',
        'alpha2': u'NA',
        'alpha3': u'NAM',
        'numeric': 516,
        'independent': True,
    },
    {
        'name': u'Nauru',
        'alpha2': u'NR',
        'alpha3': u'NRU',
        'numeric': 520,
        'independent': True,
    },
    {
        'name': u'Nepal',
        'alpha2': u'NP',
        'alpha3': u'NPL',
        'numeric': 524,
        'independent': True,
    },
    {
        'name': u'Netherlands',
        'alpha2': u'NL',
        'alpha3': u'NLD',
        'numeric': 528,
        'independent': True,
    },
    {
        'name': u'New Caledonia',
        'alpha2': u'NC',
        'alpha3': u'NCL',
        'numeric': 540,
        'independent': False,
    },
    {
        'name': u'New Zealand',
        'alpha2': u'NZ',
        'alpha3': u'NZL',
        'numeric': 554,
        'independent': True,
    },
    {
        'name': u'Nicaragua',
        'alpha2': u'NI',
        'alpha3': u'NIC',
        'numeric': 558,
        'independent': True,
    },
    {
        'name': u'Niger',
        'alpha2': u'NE',
        'alpha3': u'NER',
        'numeric': 562,
        'independent': True,
    },
    {
        'name': u'Nigeria',
        'alpha2': u'NG',
        'alpha3': u'NGA',
        'numeric': 566,
        'independent': True,
    },
    {
        'name': u'Niue',
        'alpha2': u'NU',
        'alpha3': u'NIU',
        'numeric': 570,
        'independent': False,
    },
    {
        'name': u'Norfolk Island',
        'alpha2': u'NF',
        'alpha3': u'NFK',
        'numeric': 574,
        'independent': False,
    },
    {
        'name': u'Northern Mariana Islands',
        'alpha2': u'MP',
        'alpha3': u'MNP',
        'numeric': 580,
        'independent': False,
    },
    {
        'name': u'Norway',
        'alpha2': u'NO',
        'alpha3': u'NOR',
        'numeric': 578,
        'independent': True,
    },
    {
        'name': u'Oman',
        'alpha2': u'OM',
        'alpha3': u'OMN',
        'numeric': 512,
        'independent': True,
    },
    {
        'name': u'Pakistan',
        'alpha2': u'PK',
        'alpha3': u'PAK',
        'numeric': 586,
        'independent': True,
    },
    {
        'name': u'Palau',
        'alpha2': u'PW',
        'alpha3': u'PLW',
        'numeric': 585,
        'independent': True,
    },
    {
        'name': u'"Palestine, State of"',
        'alpha2': u'PS',
        'alpha3': u'PSE',
        'numeric': 275,
        'independent': False,
    },
    {
        'name': u'Panama',
        'alpha2': u'PA',
        'alpha3': u'PAN',
        'numeric': 591,
        'independent': True,
    },
    {
        'name': u'Papua New Guinea',
        'alpha2': u'PG',
        'alpha3': u'PNG',
        'numeric': 598,
        'independent': True,
    },
    {
        'name': u'Paraguay',
        'alpha2': u'PY',
        'alpha3': u'PRY',
        'numeric': 600,
        'independent': True,
    },
    {
        'name': u'Peru',
        'alpha2': u'PE',
        'alpha3': u'PER',
        'numeric': 604,
        'independent': True,
    },
    {
        'name': u'Philippines',
        'alpha2': u'PH',
        'alpha3': u'PHL',
        'numeric': 608,
        'independent': True,
    },
    {
        'name': u'Pitcairn',
        'alpha2': u'PN',
        'alpha3': u'PCN',
        'numeric': 612,
        'independent': False,
    },
    {
        'name': u'Poland',
        'alpha2': u'PL',
        'alpha3': u'POL',
        'numeric': 616,
        'independent': True,
    },
    {
        'name': u'Portugal',
        'alpha2': u'PT',
        'alpha3': u'PRT',
        'numeric': 620,
        'independent': True,
    },
    {
        'name': u'Puerto Rico',
        'alpha2': u'PR',
        'alpha3': u'PRI',
        'numeric': 630,
        'independent': False,
    },
    {
        'name': u'Qatar',
        'alpha2': u'QA',
        'alpha3': u'QAT',
        'numeric': 634,
        'independent': True,
    },
    {
        'name': u'Réunion',
        'alpha2': u'RE',
        'alpha3': u'REU',
        'numeric': 638,
        'independent': False,
    },
    {
        'name': u'Romania',
        'alpha2': u'RO',
        'alpha3': u'ROU',
        'numeric': 642,
        'independent': True,
    },
    {
        'name': u'Russian Federation',
        'alpha2': u'RU',
        'alpha3': u'RUS',
        'numeric': 643,
        'independent': True,
    },
    {
        'name': u'Rwanda',
        'alpha2': u'RW',
        'alpha3': u'RWA',
        'numeric': 646,
        'independent': True,
    },
    {
        'name': u'Saint Barthélemy',
        'alpha2': u'BL',
        'alpha3': u'BLM',
        'numeric': 652,
        'independent': False,
    },
    {
        'name': u'"Saint Helena, Ascension and Tristan da Cunha"',
        'alpha2': u'SH',
        'alpha3': u'SHN',
        'numeric': 654,
        'independent': False,
    },
    {
        'name': u'Saint Kitts and Nevis',
        'alpha2': u'KN',
        'alpha3': u'KNA',
        'numeric': 659,
        'independent': True,
    },
    {
        'name': u'Saint Lucia',
        'alpha2': u'LC',
        'alpha3': u'LCA',
        'numeric': 662,
        'independent': True,
    },
    {
        'name': u'Saint Martin (French part)',
        'alpha2': u'MF',
        'alpha3': u'MAF',
        'numeric': 663,
        'independent': False,
    },
    {
        'name': u'Saint Pierre and Miquelon',
        'alpha2': u'PM',
        'alpha3': u'SPM',
        'numeric': 666,
        'independent': False,
    },
    {
        'name': u'Saint Vincent and the Grenadines',
        'alpha2': u'VC',
        'alpha3': u'VCT',
        'numeric': 670,
        'independent': True,
    },
    {
        'name': u'Samoa',
        'alpha2': u'WS',
        'alpha3': u'WSM',
        'numeric': 882,
        'independent': True,
    },
    {
        'name': u'San Marino',
        'alpha2': u'SM',
        'alpha3': u'SMR',
        'numeric': 674,
        'independent': True,
    },
    {
        'name': u'Sao Tome and Principe',
        'alpha2': u'ST',
        'alpha3': u'STP',
        'numeric': 678,
        'independent': True,
    },
    {
        'name': u'Saudi Arabia',
        'alpha2': u'SA',
        'alpha3': u'SAU',
        'numeric': 682,
        'independent': True,
    },
    {
        'name': u'Senegal',
        'alpha2': u'SN',
        'alpha3': u'SEN',
        'numeric': 686,
        'independent': True,
    },
    {
        'name': u'Serbia',
        'alpha2': u'RS',
        'alpha3': u'SRB',
        'numeric': 688,
        'independent': True,
    },
    {
        'name': u'Seychelles',
        'alpha2': u'SC',
        'alpha3': u'SYC',
        'numeric': 690,
        'independent': True,
    },
    {
        'name': u'Sierra Leone',
        'alpha2': u'SL',
        'alpha3': u'SLE',
        'numeric': 694,
        'independent': True,
    },
    {
        'name': u'Singapore',
        'alpha2': u'SG',
        'alpha3': u'SGP',
        'numeric': 702,
        'independent': True,
    },
    {
        'name': u'Sint Maarten (Dutch part)',
        'alpha2': u'SX',
        'alpha3': u'SXM',
        'numeric': 534,
        'independent': False,
    },
    {
        'name': u'Slovakia',
        'alpha2': u'SK',
        'alpha3': u'SVK',
        'numeric': 703,
        'independent': True,
    },
    {
        'name': u'Slovenia',
        'alpha2': u'SI',
        'alpha3': u'SVN',
        'numeric': 705,
        'independent': True,
    },
    {
        'name': u'Solomon Islands',
        'alpha2': u'SB',
        'alpha3': u'SLB',
        'numeric': 90,
        'independent': True,
    },
    {
        'name': u'Somalia',
        'alpha2': u'SO',
        'alpha3': u'SOM',
        'numeric': 706,
        'independent': True,
    },
    {
        'name': u'South Africa',
        'alpha2': u'ZA',
        'alpha3': u'ZAF',
        'numeric': 710,
        'independent': True,
    },
    {
        'name': u'South Georgia and the South Sandwich Islands',
        'alpha2': u'GS',
        'alpha3': u'SGS',
        'numeric': 239,
        'independent': False,
    },
    {
        'name': u'South Sudan',
        'alpha2': u'SS',
        'alpha3': u'SSD',
        'numeric': 728,
        'independent': True,
    },
    {
        'name': u'Spain',
        'alpha2': u'ES',
        'alpha3': u'ESP',
        'numeric': 724,
        'independent': True,
    },
    {
        'name': u'Sri Lanka',
        'alpha2': u'LK',
        'alpha3': u'LKA',
        'numeric': 144,
        'independent': True,
    },
    {
        'name': u'Sudan',
        'alpha2': u'SD',
        'alpha3': u'SDN',
        'numeric': 729,
        'independent': True,
    },
    {
        'name': u'Suriname',
        'alpha2': u'SR',
        'alpha3': u'SUR',
        'numeric': 740,
        'independent': True,
    },
    {
        'name': u'Svalbard and Jan Mayen',
        'alpha2': u'SJ',
        'alpha3': u'SJM',
        'numeric': 744,
        'independent': False,
    },
    {
        'name': u'Swaziland',
        'alpha2': u'SZ',
        'alpha3': u'SWZ',
        'numeric': 748,
        'independent': True,
    },
    {
        'name': u'Sweden',
        'alpha2': u'SE',
        'alpha3': u'SWE',
        'numeric': 752,
        'independent': True,
    },
    {
        'name': u'Switzerland',
        'alpha2': u'CH',
        'alpha3': u'CHE',
        'numeric': 756,
        'independent': True,
    },
    {
        'name': u'Syrian Arab Republic',
        'alpha2': u'SY',
        'alpha3': u'SYR',
        'numeric': 760,
        'independent': True,
    },
    {
        'name': u'"Taiwan, Province of China[a]"',
        'alpha2': u'TW',
        'alpha3': u'TWN',
        'numeric': 158,
        'independent': False,
    },
    {
        'name': u'Tajikistan',
        'alpha2': u'TJ',
        'alpha3': u'TJK',
        'numeric': 762,
        'independent': True,
    },
    {
        'name': u'"Tanzania, United Republic of"',
        'alpha2': u'TZ',
        'alpha3': u'TZA',
        'numeric': 834,
        'independent': True,
    },
    {
        'name': u'Thailand',
        'alpha2': u'TH',
        'alpha3': u'THA',
        'numeric': 764,
        'independent': True,
    },
    {
        'name': u'Timor-Leste',
        'alpha2': u'TL',
        'alpha3': u'TLS',
        'numeric': 626,
        'independent': True,
    },
    {
        'name': u'Togo',
        'alpha2': u'TG',
        'alpha3': u'TGO',
        'numeric': 768,
        'independent': True,
    },
    {
        'name': u'Tokelau',
        'alpha2': u'TK',
        'alpha3': u'TKL',
        'numeric': 772,
        'independent': False,
    },
    {
        'name': u'Tonga',
        'alpha2': u'TO',
        'alpha3': u'TON',
        'numeric': 776,
        'independent': True,
    },
    {
        'name': u'Trinidad and Tobago',
        'alpha2': u'TT',
        'alpha3': u'TTO',
        'numeric': 780,
        'independent': True,
    },
    {
        'name': u'Tunisia',
        'alpha2': u'TN',
        'alpha3': u'TUN',
        'numeric': 788,
        'independent': True,
    },
    {
        'name': u'Turkey',
        'alpha2': u'TR',
        'alpha3': u'TUR',
        'numeric': 792,
        'independent': True,
    },
    {
        'name': u'Turkmenistan',
        'alpha2': u'TM',
        'alpha3': u'TKM',
        'numeric': 795,
        'independent': True,
    },
    {
        'name': u'Turks and Caicos Islands',
        'alpha2': u'TC',
        'alpha3': u'TCA',
        'numeric': 796,
        'independent': False,
    },
    {
        'name': u'Tuvalu',
        'alpha2': u'TV',
        'alpha3': u'TUV',
        'numeric': 798,
        'independent': True,
    },
    {
        'name': u'Uganda',
        'alpha2': u'UG',
        'alpha3': u'UGA',
        'numeric': 800,
        'independent': True,
    },
    {
        'name': u'Ukraine',
        'alpha2': u'UA',
        'alpha3': u'UKR',
        'numeric': 804,
        'independent': True,
    },
    {
        'name': u'United Arab Emirates',
        'alpha2': u'AE',
        'alpha3': u'ARE',
        'numeric': 784,
        'independent': True,
    },
    {
        'name': u'United Kingdom of Great Britain and Northern Ireland',
        'alpha2': u'GB',
        'alpha3': u'GBR',
        'numeric': 826,
        'independent': True,
    },
    {
        'name': u'United States of America',
        'alpha2': u'US',
        'alpha3': u'USA',
        'numeric': 840,
        'independent': True,
    },
    {
        'name': u'United States Minor Outlying Islands',
        'alpha2': u'UM',
        'alpha3': u'UMI',
        'numeric': 581,
        'independent': False,
    },
    {
        'name': u'Uruguay',
        'alpha2': u'UY',
        'alpha3': u'URY',
        'numeric': 858,
        'independent': True,
    },
    {
        'name': u'Uzbekistan',
        'alpha2': u'UZ',
        'alpha3': u'UZB',
        'numeric': 860,
        'independent': True,
    },
    {
        'name': u'Vanuatu',
        'alpha2': u'VU',
        'alpha3': u'VUT',
        'numeric': 548,
        'independent': True,
    },
    {
        'name': u'Venezuela (Bolivarian Republic of)',
        'alpha2': u'VE',
        'alpha3': u'VEN',
        'numeric': 862,
        'independent': True,
    },
    {
        'name': u'Viet Nam',
        'alpha2': u'VN',
        'alpha3': u'VNM',
        'numeric': 704,
        'independent': True,
    },
    {
        'name': u'Virgin Islands (British)',
        'alpha2': u'VG',
        'alpha3': u'VGB',
        'numeric': 92,
        'independent': False,
    },
    {
        'name': u'Virgin Islands (U.S.)',
        'alpha2': u'VI',
        'alpha3': u'VIR',
        'numeric': 850,
        'independent': False,
    },
    {
        'name': u'Wallis and Futuna',
        'alpha2': u'WF',
        'alpha3': u'WLF',
        'numeric': 876,
        'independent': False,
    },
    {
        'name': u'Western Sahara',
        'alpha2': u'EH',
        'alpha3': u'ESH',
        'numeric': 732,
        'independent': False,
    },
    {
        'name': u'Yemen',
        'alpha2': u'YE',
        'alpha3': u'YEM',
        'numeric': 887,
        'independent': True,
    },
    {
        'name': u'Zambia',
        'alpha2': u'ZM',
        'alpha3': u'ZMB',
        'numeric': 894,
        'independent': True,
    },
    {
        'name': u'Zimbabwe',
        'alpha2': u'ZW',
        'alpha3': u'ZWE',
        'numeric': 716,
        'independent': True,
    },
]


def by_name(name):
    for country in countries_data:
        if name.lower() == country['name'].lower():
            return country
    else:
        return None


def by_alpha2(alpha2):
    for country in countries_data:
        if alpha2.lower() == country['alpha2'].lower():
            return country
    else:
        return None


def by_alpha3(alpha3):
    for country in countries_data:
        if alpha3.lower() == country['alpha3'].lower():
            return country
    else:
        return None


def by_numeric(numeric):
    for country in countries_data:
        if numeric == country['numeric']:
            return country
    else:
        return None
